services:
  redis:
    image: redis:7.4-alpine
    container_name: resilix-redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  prometheus:
    image: prom/prometheus:v3.4.0
    container_name: resilix-prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - redis

  jaeger:
    image: jaegertracing/all-in-one:1.67.0
    container_name: resilix-jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  grafana:
    image: grafana/grafana:12.0.0
    container_name: resilix-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./observability/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    depends_on:
      - prometheus
      - jaeger
